    <!-- BEGIN: Content-->
    <div class="app-content content ">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper">
            <!-- <div class="content-header row">
                <div class="content-header-left col-md-9 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="col-12">
                            <h2 class="content-header-title float-left mb-0">
                                <b><?php foreach ($_SESSION['submenus'] as $menu) { ?>
                                        <?php if ($this->_controlador == $menu['v_link']) {
                                            echo $menu['v_descripcion'];
                                        } else {
                                            '';
                                        } ?>
                                    <?php } ?>
                                </b>
                            </h2>
                        </div>
                    </div>
                </div>
            </div> -->


            <div class="content-body" style="color:rgb(248, 248, 248);">
                <section id="basic-horizontal-layouts" style="color:rgb(248, 248, 248);">
                    <div class="row">
                        <div class="col-md-12 col-12" style="color:rgb(248, 248, 248);">
                            <div class="card bg-light-secondary text-white">

                                <div class="card-header bg-gradient-success" style="height:50px;">
                                    <h4 class="alert-heading" style="color:#133337"><i class="fas fa-chart-pie"></i> <strong>ESTADISTICAS</strong> </h4>
                                </div>
                                <div class="row">
                                    <div class="form-group col-md-12">
                                    </div>
                                </div>

                                <input type="hidden" id="hora">
                                <div class="card col-12">
                                    <div class="card-body">

                                        <div class="col-xs-12 col-sm-12 col-12">
                                            <form action="<?php echo BASE_URL ?>fuerzaventa/venta_supervisor" method="post">
                                                <div class="row">
                                                    <div class="col-sm-4">
                                                        <div class="form-group">
                                                            <label class="form-label font-weight-bolder">Fecha filtro</label>
                                                            <div class="input-group date" id="ffin" data-target-input="nearest">
                                                                <input type="text" name="fechaini" id="fechaini" class="form-control flatpickr-basic flatpickr-input" placeholder="YYYY-MM-DD" readonly=" readonly" />
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-sm-4">
                                                        <div class="form-group">
                                                            <label style="height:15px;">.</label>
                                                            <button type="submit" id="btn_filtrar" class="btn btn-relief-primary col-md-12"><i data-feather='filter'></i> Filtrar</button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>

                                        <div class="col-xs-12 col-sm-12 col-12">
                                            <table id="example1" class="table table-bordered">
                                                <thead class="thead-dark">
                                                    <tr class="text-center">
                                                        <th>DATOS VENTA DEL VENDEDOR</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <?php if (isset($this->ListadoVentaSupervisor)) { ?>
                                                        <?php foreach ($this->ListadoVentaSupervisor as $vn) { ?>
                                                            <tr>
                                                                <td class="text-center">
                                                                    <div class="card-body statistics-body">
                                                                        <div class="row">
                                                                            <div class="col-md-3 col-sm-6 col-12 mb-2 mb-md-0">
                                                                                <div class="media">
                                                                                    <div class="avatar bg-light-primary  mr-0">
                                                                                        <div class="avatar-content">
                                                                                            <i data-feather="trending-up" stroke-width="3" class="avatar-icon"></i>
                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="media-body my-auto">
                                                                                        <h4 class="font-weight-bolder mb-0"><?php echo $vn['Numero_ventas'] ?></h4>
                                                                                        <p class="card-text font-small-3 mb-0" style="color:#133337">(#.) de Ventas</p>
                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                            <div class="col-md-3 col-sm-6 col-12 mb-2 mb-md-0">
                                                                                <div class="media">
                                                                                    <div class="avatar bg-light-info mr-0">
                                                                                        <div class="avatar-content">
                                                                                            <i data-feather="user" stroke-width="3" class="avatar-icon"></i>
                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="media-body my-auto">
                                                                                        <h4 class="font-weight-bolder mb-0"><?php echo $vn['Cantidad_clientes'] ?></h4>
                                                                                        <p class="card-text font-small-3 mb-0" style="color:#133337">(#.) de Clientes</p>
                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                            <div class="col-md-3 col-sm-6 col-12 mb-2 mb-sm-0">
                                                                                <div class="media">
                                                                                    <div class="avatar bg-light-danger mr-0">
                                                                                        <div class="avatar-content">
                                                                                            <i data-feather="box" stroke-width="3" class="avatar-icon"></i>
                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="media-body my-auto">
                                                                                        <h4 class="font-weight-bolder mb-0"><?php echo $vn['Cantidad_productos'] ?></h4>
                                                                                        <p class="card-text font-small-3 mb-0" style="color:#133337">(#.) de Productos</p>
                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                            <div class="col-md-3 col-sm-6 col-12">
                                                                                <div class="media">
                                                                                    <div class="avatar bg-light-success mr-0">
                                                                                        <div class="avatar-content">
                                                                                            <i data-feather="dollar-sign" stroke-width="3" class="avatar-icon"></i>
                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="media-body my-auto">
                                                                                        <h4 class="font-weight-bolder mb-0"><?php echo $vn['Monto_Soles'] ?></h4>
                                                                                        <p class="card-text font-small-3 mb-0" style="color:#133337">(#.) Ingresos</p>
                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                </td>
                                                                <td class="text-left"><b> <?php echo $vn['ch_CodVende'] ?>-<?php echo $vn['vc_nomvende'] ?>  (<?php echo $vn['v_fecha'] ?>) </b> </td>
                                                            </tr>
                                                        <?php } ?>
                                                    <?php } ?>
                                                </tbody>
                                            </table>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
    <!-- END: Content-->