<!DOCTYPE html>
<html class="loading" lang="en" data-textdirection="ltr">
<!-- BEGIN: Head-->

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=0,minimal-ui">
    <meta name="description" content="Vuexy admin is super flexible, powerful, clean &amp; modern responsive bootstrap 4 admin template with unlimited possibilities.">
    <meta name="keywords" content="admin template, Vuexy admin template, dashboard template, flat admin template, responsive admin template, web app">
    <meta name="author" content="PIXINVENT">
    <title>Verdum Perú SAC (Inicio de sesión)</title>
    <!-- <link rel="shortcut icon" type="image/x-icon" href="<?php //echo BASE_URL 
                                                                ?>public/dist/img/favicon.ico"> -->
    <link rel="shortcut icon" type="image/x-icon" href="<?php echo BASE_URL ?>public/dist/img/favicon.png">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;1,400;1,500;1,600" rel="stylesheet">


    <!-- BEGIN: Vendor CSS-->
    <?php if (isset($_layoutParams['cssSp']) && count($_layoutParams['cssSp'])) : ?>
        <?php foreach ($_layoutParams['cssSp'] as $layoutcssSp) : ?>
            <link rel="stylesheet" href="<?php echo  $layoutcssSp ?>">
        <?php endforeach; ?>
    <?php endif; ?>
    <!-- END: Page CSS-->

</head>
<!-- END: Head-->

<!-- BEGIN: Body-->

<body class="horizontal-layout horizontal-menu blank-page navbar-floating footer-static" data-open="hover" data-menu="horizontal-menu" data-col="blank-page">
    <!-- BEGIN: Content-->
    <div class="app-content content ">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper">
            <div class="content-header row">
            </div>
            <div class="content-body">
                <div class="auth-wrapper auth-v1 px-2">

                    <!-- <div class="auth-inner py-0"> -->
                    <div class="auth-inner">
                        <!-- Login v1 -->
                        <div class="card mb-0">
                            <div class="card-body">
                                <!-- Brand logo-->
                                <a class="brand-logo">
                                    <svg viewBox="0 0 139 100" version="1.1" height="30">
                                        <defs>
                                            <lineargradient id="linearGradient-1" x1="100%" y1="10.5120544%" x2="50%" y2="89.4879456%">
                                                <stop stop-color="#000000" offset="0%"></stop>
                                                <stop stop-color="#FFFFFF" offset="100%"></stop>
                                            </lineargradient>
                                            <lineargradient id="linearGradient-2" x1="64.0437835%" y1="46.3276743%" x2="37.373316%" y2="100%">
                                                <stop stop-color="#EEEEEE" stop-opacity="0" offset="0%"></stop>
                                                <stop stop-color="#FFFFFF" offset="100%"></stop>
                                            </lineargradient>
                                        </defs>

                                        <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                            <g id="Artboard" transform="translate(-400.000000, -178.000000)">
                                                <g id="Group" transform="translate(400.000000, 178.000000)">
                                                    <path class="brand-text text-success" id="Path" d="M-5.68434189e-14,2.84217094e-14 L39.1816085,2.84217094e-14 L69.3453773,32.2519224 L101.428699,2.84217094e-14 L138.784583,2.84217094e-14 L138.784199,29.8015838 C137.958931,37.3510206 135.784352,42.5567762 132.260463,45.4188507 C128.736573,48.2809251 112.33867,64.5239941 83.0667527,94.1480575 L56.2750821,94.1480575 L6.71554594,44.4188507 C2.46876683,39.9813776 0.345377275,35.1089553 0.345377275,29.8015838 C0.345377275,24.4942122 0.230251516,14.560351 -5.68434189e-14,2.84217094e-14 Z" style="fill: currentColor"></path>
                                                    <path id="Path1" d="M69.3453773,32.2519224 L101.428699,1.42108547e-14 L138.784583,1.42108547e-14 L138.784199,29.8015838 C137.958931,37.3510206 135.784352,42.5567762 132.260463,45.4188507 C128.736573,48.2809251 112.33867,64.5239941 83.0667527,94.1480575 L56.2750821,94.1480575 L32.8435758,70.5039241 L69.3453773,32.2519224 Z" fill="url(#linearGradient-1)" opacity="0.2"></path>
                                                    <polygon id="Path-2" fill="#000000" opacity="0.049999997" points="69.3922914 32.4202615 32.8435758 70.5039241 54.0490008 16.1851325">
                                                    </polygon>
                                                    <polygon id="Path-21" fill="#000000" opacity="0.099999994" points="69.3922914 32.4202615 32.8435758 70.5039241 58.3683556 20.7402338">
                                                    </polygon>
                                                    <polygon id="Path-3" fill="url(#linearGradient-2)" opacity="0.099999994" points="101.428699 0 83.0667527 94.1480575 130.378721 47.0740288">
                                                    </polygon>
                                                </g>
                                            </g>
                                        </g>
                                    </svg>
                                </a>

                                <a class="brand-logo">
                                    <h3 class="brand-text text-success ml-1">VERDUM PERU SAC</h3>
                                </a>

                                <h4 class="card-title mb-1">Iniciar sesión...</h4>
                                <!-- <p class="card-text mb-2">Por favor inicie sesión, sino crear una nueva cuenta.</p> -->

                                <form role="form">
                                    <div class="form-group">
                                        <label for="correo" class="form-label font-weight-bolder">Usuario</label>
                                        <input id="correo" type="text" class="form-control" placeholder="username" tabindex="1" autofocus autocomplete="off" />
                                    </div>

                                    <div class="form-group">
                                        <div class="d-flex justify-content-between font-weight-bolder">
                                            <label for="login-password">Contraseña</label>
                                        </div>
                                        <div class="input-group input-group-merge form-password-toggle">
                                            <input id="clave" onkeypress="pulsar(event)" type="password" class="form-control form-control-merge" name="login-password" tabindex="2" placeholder="&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;" />
                                            <div class="input-group-append">
                                                <span class="input-group-text cursor-pointer"><i data-feather="eye"></i></span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <button id="btnlogin" type="button" class="btn btn-success btn-block" tabindex="3">Iniciar sesión</button>
                                    </div>
                                </form>

                                <p class="text-center mt-2">
                                    <span>Eres usuario nuevo?</span>
                                    <!-- <a href="page-auth-register-v1.html"> -->
                                    <a href="<?php echo BASE_URL ?>index/registro"><span>Crear una cuenta</span></a>
                                    <br>
                                    <span>Olvidastes tu clave?</span>
                                    <!-- <a href="page-auth-register-v1.html"> -->
                                    <a href="<?php echo BASE_URL ?>index/recuperarclave"><span>Recuperar mi
                                            contraseña</span></a>
                                </p>

                            </div>
                        </div>
                        <!-- /Login v1 -->
                    </div>


                </div>
            </div>
        </div>

    </div>
    <!-- END: Content-->


    <!-- BEGIN: Llamada a JS-->
    <?php if (isset($_layoutParams['jsSp']) && count($_layoutParams['jsSp'])) : ?>
        <?php foreach ($_layoutParams['jsSp'] as $layoutjsSp) : ?>
            <script src="<?php echo  $layoutjsSp ?>" type="text/javascript"></script>
        <?php endforeach; ?>
    <?php endif; ?>
    <!-- END: Llamada a JS-->

    <script>
        $(window).on('load', function() {
            if (feather) {
                feather.replace({
                    width: 14,
                    height: 14
                });
            }
        })
    </script>

    <?php if (isset($_layoutParams['js']) && count($_layoutParams['js'])) : ?>
        <?php foreach ($_layoutParams['js'] as $layout) : ?>
            <script src="<?php echo  $layout ?>" type="text/javascript"></script>
        <?php endforeach; ?>
    <?php endif; ?>


    <!-- BEGIN: Dark Mode Switcher-->
    <!-- <div data-url="index.phtml" class="dark-mode-switcher cursor-pointer shadow-md fixed bottom-0 right-0 box dark:bg-dark-2 border rounded-full w-40 h-12 flex items-center justify-center z-50 mb-10 mr-10">
        <div class="mr-1 text-success dark:text-gray-300">Dark Mode</div>
        <div class="dark-mode-switcher__toggle border"></div>
    </div> -->

    <!-- <script src="https://maps.googleapis.com/maps/api/js?key=[" your-google-map-api"]&libraries=places"></script>
    <script src="dist/js/app.js"></script> -->


</body>
<!-- END: Body-->

</html>