<!-- BEGIN: Content-->
<div class="app-content content ">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper">
        <div class="content-header row">
            <div class="content-header-left col-md-9 col-12 mb-2">
                <div class="row breadcrumbs-top">
                    <div class="col-12">
                        <h2 class="content-header-title float-left mb-0">
                            <b><?php foreach ($_SESSION['menus'] as $menu) { ?>
                                    <?php if ($this->_controlador == $menu['v_link']) {
                                        echo $menu['v_descripcion'];
                                    } else {
                                        '';
                                    } ?>
                                <?php } ?>
                            </b>
                        </h2>
                    </div>
                </div>
            </div>
        </div>



        <section id="input-group-basic">

            <div class="row">


                <div class="col-md-6">
                    <div class="card-header bg-gradient-dark" style="height:52px;">
                        <h4 class="card-title text-white"><b>Cargar archivo (*.xls,*.xlsx)</b></h4>
                    </div>

                    <div class="card">
                        <div class="card-body">
                            <div class="row">

                                <div class="col-sm-6">
                                    <div class="alert-success form-group">
                                        <div class="input-group">
                                            <input id="documento" name="documento" type="file">
                                        </div>
                                    </div>
                                </div>

                                <div class="col-sm-4">
                                    <div class="form-group">
                                        <button id="btnsubir" type="button" class="btn btn-success btn-block font-weight-bolder" style="color: White;">
                                            <i class="fa-solid fa-upload fa-beat"></i>
                                            <span>&nbsp;&nbsp;Subir archivo</span>
                                        </button>
                                    </div>
                                </div>

                                <div class="col-sm-2">
                                    <div class="form-group">
                                        <button id="btnEliminar" type="button" class="btn btn-danger btn-block font-weight-bolder" style="color: White;">
                                            <i class="fa-solid fa-trash-can fa-beat"></i>
                                        </button>
                                    </div>
                                </div>
                            </div>
                            </form>

                        </div>

                    </div>
                </div>


                <div class="col-md-6">
                    <div class="card-header bg-gradient-dark" style="height:52px;">
                        <h4 class="card-title text-white"><b>#Opciones</b></h4>
                    </div>
                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                
                                <form action="<?php echo BASE_URL ?>canalcliente/descargar_formato" method="post">
                                    <div class="form-group">
                                        <div class="col-md-12">
                                            <button id="btnformato" type="submit" class="btn btn-success btn-block font-weight-bolder" style="color: White;">
                                                <i class="fa-solid fa-file-excel fa-beat"></i>
                                                <span>&nbsp;&nbsp;Descargar formato Excel</span>
                                            </button>
                                        </div>
                                    </div>
                                </form>

                                <form>
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <div class="d-flex align-items-center mb-1">
                                                <span class="title">Periodo:&nbsp;</span>
                                                <select id="periodo" class="select2 form-control form-control-lg">
                                                    <?php foreach ($this->ListadoPeriodo as $pr) { ?>
                                                        <option <?php echo $pr['v_default']; ?> value="<?php  echo  $pr['i_id']; ?>"><?php echo $pr['v_perpost']; ?>&nbsp;&nbsp;&nbsp;&nbsp;</option>
                                                    <?php } ?>
                                                </select>
                                            </div>

                                        </div>
                                    </div>
                                </form>

                                <form>
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <button id="btnSistema" type="button" class="btn btn-primary btn-block font-weight-bolder">
                                                <i class="fa-solid fa-share-from-square fa-beat"></i>
                                                <span>Actualizar en sistema</span>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>


        <div class="row">
            <section class="col-lg-12">
                <div class="card col-12">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12 col-12">
                                <table id="example1" class="table table-bordered">
                                    <thead class="thead-dark">
                                        <tr class="text-center">
                                            <th>#ID Cliente</th>
                                            <th>#ID Direccion</th>
                                            <th>Nombre Canal</th>
                                            <th>Nombre SubCanal</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php if (isset($this->canales)) { ?>
                                            <?php foreach ($this->canales as $cn) { ?>
                                                <tr>
                                                    <!-- <td class="text-center"><?php echo $cn['v_ruc'] ?></td> -->
                                                    <td class="text-center">
                                                        <b> <span class="badge bg-pill  badge-light-success"><?php echo $cn['v_ruc'] ?></span></b>
                                                    </td>
                                                    <td class="text-left"> <strong> <?php echo $cn['v_id_direccion'] ?></strong></td>
                                                    <td class="text-center"><?php echo $cn['v_nombre_canal'] ?></td>
                                                    <td class="text-center"><?php echo $cn['v_nombre_subcanal'] ?></td>
                                                </tr>
                                            <?php } ?>
                                        <?php } ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>

    </div>
</div>
<!-- END: Content-->

<!-- MODAL INSERTANDO -->
<div class="modal fade" id="modal-insert" data-backdrop="static" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">CARGANDO DATOS...</h5>
                <!-- <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button> -->
            </div>
            <div class="modal-body">
                <p>
                    Se estan cargando los datos, favor de no cerrar la ventana
                </p>
                <p>
                    Tiempo transcurrido: <b id="number"></b> segundos
                </p>
            </div>
        </div>
    </div>
</div>