    <!-- BEGIN: Content-->
    <div class="app-content content ">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper">

            <div class="content-body" style="color:rgb(248, 248, 248);">
                <section id="basic-horizontal-layouts" style="color:rgb(248, 248, 248);">
                    <div class="row">
                        <div class="col-md-12 col-12" style="color:rgb(248, 248, 248);">
                            <div class="card bg-light-secondary text-white">
                                <input type="hidden" id="hora">
                                <div class="card col-12">
                                    <div class="card-header border-bottom p-1">
                                        <div class="head-label">
                                            <h6 class="mb-0"></h6>
                                        </div>
                                        <div class="dt-action-buttons text-right">
                                            <div class="dt-buttons d-inline-flex">
                                                <button id="btnagregar" type="button" class="dt-button create-new btn btn-primary"><i class="fa-solid fa-user-plus fa-beat"></i>&nbsp; NUEVO USUARIO </button>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="card-header">
                                        <h4 class="card-title"> <i class="fa-solid fa-list"></i></i> <strong>Administracion de Zonas de Ruta</strong> </h4>
                                    </div>

                                    <div class="card-body">
                                        <div class="col-xs-12 col-sm-12 col-12">
                                            <table id="example1" class="table table-sm">
                                                <thead class="thead-dark">
                                                    <tr class="text-center">
                                                        <th>VENDEDOR</th>
                                                        <th>LOCAL</th>
                                                        <th>ZONA VENTA</th>
                                                        <th>REVISAR</th>
                                                        <th>SUPERVISOR VENDEDORES</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <?php if (isset($this->ListadoVendedorZonaRuta)) { ?>
                                                        <?php foreach ($this->ListadoVendedorZonaRuta as $vn) { ?>
                                                            <tr>
                                                                <td class="text-left">
                                                                    <div class="col-md-6 col-sm-6 col-12 mb-2 mb-md-0">
                                                                        <div class="media">
                                                                            <div class="avatar bg-light-info mr-0">
                                                                                <div class="avatar-content">
                                                                                    <i data-feather="user" stroke-width="3" class="avatar-icon"></i>
                                                                                </div>
                                                                            </div>
                                                                            <div class="media-body my-auto">
                                                                                <h5 class="font-weight-bolder mb-0"><?php echo $vn['v_codvend'] ?>-<?php echo $vn['v_name'] ?></h5>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                </td>
                                                                <td class="text-center">
                                                                    <b> <?php echo $vn['v_sede'] ?></b>
                                                                </td>
                                                                <td class="text-center">
                                                                    <b> <?php echo $vn['v_zonaventa'] ?></b>
                                                                </td>
                                                                <td class='text-center'>
                                                                    <a id='<?php echo $vn['v_codvend'] ?>' <?php $variable1 =  $vn['v_codvend'] ?> <?php $variable2 =  $vn['v_name'] ?><?php $variable3 =  $vn['v_zonaventa'] ?> href="<?php echo BASE_URL ?><?php echo $vn['v_url'] ?>=<?php echo urlencode($variable1); ?>&variable2=<?php echo utf8_decode(urlencode($variable2)); ?>&variable3=<?php echo utf8_decode(urlencode($variable3)); ?>" class="btn btn-<?php echo $vn['v_btn1'] ?>"><i class="fas fa-<?php echo $vn['v_btn1Imagen'] ?>"></i></a>                                            
                                                                </td>
                                                                <td class="text-left"><b> <?php echo $vn['v_codsup'] ?> - <?php echo $vn['v_namesup'] ?> </b> </td>
                                                            </tr>
                                                        <?php } ?>
                                                    <?php } ?>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>


                                <div class="card col-12">
                                    <div class="card-header">
                                        <h4 class="card-title">Rutas del Vendedor</h4>
                                        <i data-feather="more-vertical" class="font-medium-3 cursor-pointer"></i>
                                    </div>
                                    <div class="card-body">
                                        <div class="col-xs-12 col-sm-12 col-12">
                                            <table id="example2" class="table table-sm">
                                                <thead class="thead-dark">
                                                    <tr class="text-center">
                                                        <th>SUPERVISOR</th>
                                                        <th>VENDEDOR</th>
                                                        <th>LUNES</th>
                                                        <th>MARTES</th>
                                                        <th>MIERCOLES</th>
                                                        <th>JUEVES</th>
                                                        <th>VIERNES</th>
                                                        <th>SABADO</th>
                                                        <th>DOMINGO</th>
                                                        <th>ZONA VENTA</th>
                                                        <th>DEPARTAMENTO</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <?php if (isset($this->ListadoSemanaRutaSupervisor)) { ?>
                                                        <?php foreach ($this->ListadoSemanaRutaSupervisor as $vn) { ?>
                                                            <tr>

                                                                <td class="text-left"><b> <?php echo $vn['v_codsup'] ?> - <?php echo $vn['v_namesup'] ?> </b> </td>

                                                                <td class="text-left">
                                                                    <div class="col-md-12 col-sm-6 col-12 mb-2 mb-md-0">
                                                                        <div class="media">
                                                                            <div class="avatar bg-light-info mr-0">
                                                                                <div class="avatar-content">
                                                                                    <i data-feather="user" stroke-width="3" class="avatar-icon"></i>
                                                                                </div>
                                                                            </div>
                                                                            <div class="media-body my-auto">
                                                                                <h5 class="font-weight-bolder mb-0"><?php echo $vn['v_codvend'] ?>-<?php echo $vn['v_name'] ?></h5>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                </td>
                                                                <td class="text-center">
                                                                    <b> <span class="badge bg-pill  badge-light-success"><?php echo $vn['Lunes'] ?></span></b>
                                                                </td>
                                                                <td class="text-center">
                                                                    <b> <span class="badge bg-pill  badge-light-success"><?php echo $vn['Martes'] ?></span></b>
                                                                </td>
                                                                <td class="text-center">
                                                                    <b> <span class="badge bg-pill  badge-light-success"><?php echo $vn['Miercoles'] ?></span></b>
                                                                </td>
                                                                <td class="text-center">
                                                                    <b> <span class="badge bg-pill  badge-light-success"><?php echo $vn['Jueves'] ?></span></b>
                                                                </td>
                                                                <td class="text-center">
                                                                    <b> <span class="badge bg-pill  badge-light-success"><?php echo $vn['Viernes'] ?></span></b>
                                                                </td>
                                                                <td class="text-center">
                                                                    <b> <span class="badge bg-pill  badge-light-success"><?php echo $vn['Sabado'] ?></span></b>
                                                                </td>
                                                                <td class="text-center">
                                                                    <b> <span class="badge bg-pill  badge-light-success"><?php echo $vn['Domingo'] ?></span></b>
                                                                </td>
                                                                <td class="text-center">
                                                                    <b> <?php echo $vn['ZonaVentaID'] ?></b>
                                                                </td>
                                                                <td class="text-center">
                                                                    <b> <?php echo $vn['departamento'] ?></b>
                                                                </td>
                                                            </tr>
                                                        <?php } ?>
                                                    <?php } ?>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
    <!-- END: Content-->