    <!-- BEGIN: Content-->
    <div class="app-content content ">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-9 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="col-12">
                            <h2 class="content-header-title float-left mb-0">
                                <b>Configuracion de accesos perfil</b>
                            </h2>
                        </div>
                    </div>
                </div>
            </div>

            <div class="content-body">
                <!-- Basic Horizontal form layout section start -->
                <section id="basic-horizontal-layouts">
                    <div class="row">
                        <div class="col-md-6 col-12">
                            <div class="card">
                                <div class="card-header">
                                    <h4 class="card-title">Asignar Menu</h4>
                                </div>
                                <div class="card-body">
                                    <form class="form form-horizontal">
                                        <div class="row">
                                            <div class="col-12">
                                                <div class="form-group row">
                                                    <div class="col-sm-12">
                                                        <table id="example" class="table table-bordered">
                                                            <thead class="thead-dark">
                                                                <tr class="text-center">
                                                                    <th>#</th>
                                                                    <th>Nombre</th>
                                                                    <th>Submenu</th>
                                                                    <th>Status</th>
                                                                    <th>Perfil</th>
                                                                </tr>
                                                            </thead>
                                                            <tbody>
                                                            </tbody>
                                                        </table>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-sm-9 offset-sm-4">
                                                <button type="reset" id="AsignarMenu" class="btn btn-relief-success"><i data-feather='save'></i> Asignar</button>
                                                <button type="reset" class="btn btn-relief-secondary">Cancelar</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-6 col-12">
                            <div class="card">
                                <div class="card-header">
                                    <h4 class="card-title">Menus Asignados</h4>
                                </div>
                                <div class="card-body">
                                    <form class="form form-horizontal">
                                        <div class="row">
                                            <div class="col-12">
                                                <div class="form-group row">
                                                    <div class="col-sm-12">
                                                        <table id="example1" class="table table-bordered">
                                                            <thead class="thead-dark">
                                                                <tr class="text-center">
                                                                    <th>#</th>
                                                                    <th>Nombre</th>
                                                                    <th>Submenu</th>
                                                                    <th>Status</th>
                                                                    <th>Perfil</th>
                                                                </tr>
                                                            </thead>
                                                            <tbody>
                                                            </tbody>
                                                        </table>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-sm-9 offset-sm-3">
                                                <button type="reset" id="QuitarMenu" class="btn btn-relief-danger"><i data-feather='delete'></i> Quitar</button>
                                                <button type="reset" class="btn btn-relief-secondary"><i data-feather='delete'></i> Cancelar</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <!-- Basic Horizontal form layout section end -->
                <!-- Basic Horizontal form layout section start -->
                <section id="basic-horizontal-layouts">
                    <div class="row">
                        <div class="col-md-6 col-12">
                            <div class="card">
                                <div class="card-header">
                                    <h4 class="card-title">Asignar SubMenu</h4>
                                </div>
                                <div class="card-body">
                                    <form class="form form-horizontal">
                                        <div class="row">
                                            <div class="col-12">
                                                <div class="form-group row">
                                                    <div class="col-sm-12">
                                                        <table id="example2" class="table table-bordered">
                                                            <thead class="thead-dark">
                                                                <tr class="text-center">
                                                                    <th>#</th>
                                                                    <th>Nombre</th>
                                                                    <th>Submenu</th>
                                                                    <th>Status</th>
                                                                    <th>Perfil</th>
                                                                </tr>
                                                            </thead>
                                                            <tbody>
                                                            </tbody>
                                                        </table>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-sm-9 offset-sm-4">
                                                <button type="reset" id="AsignarSubMenu" class="btn btn-relief-success"><i data-feather='save'></i> Asignar</button>
                                                <button type="reset" class="btn btn-relief-secondary"> <i data-feather='delete'></i> Cancelar</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-6 col-12">
                            <div class="card">
                                <div class="card-header">
                                    <h4 class="card-title">SubMenus Asignados</h4>
                                </div>
                                <div class="card-body">
                                    <form class="form form-horizontal">
                                        <div class="row">
                                            <div class="col-12">
                                                <div class="form-group row">
                                                    <div class="col-sm-12">
                                                        <table id="example3" class="table table-bordered">
                                                            <thead class="thead-dark">
                                                                <tr class="text-center">
                                                                    <th>#</th>
                                                                    <th>Nombre</th>
                                                                    <th>Submenu</th>
                                                                    <th>Status</th>
                                                                    <th>Perfil</th>
                                                                </tr>
                                                            </thead>
                                                            <tbody>
                                                            </tbody>
                                                        </table>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-sm-9 offset-sm-3">
                                                <button type="reset" id="QuitarSubMenu" class="btn btn-relief-danger"><i data-feather='delete'></i> Quitar</button>
                                                <button type="reset" class="btn btn-relief-secondary"><i data-feather='delete'></i> Cancelar</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <!-- Basic Horizontal form layout section end -->
            </div>
        </div>
    </div>
    <!-- END: Content-->